chore: commit hook for lint
FEMessage/element pull request #13
Opened 2019-11-14 09:21 UTC by lianghx-319

## Test
![image](https://user-images.githubusercontent.com/27187946/68843470-20836600-0703-11ea-9caa-0cef3eb9a8c6.png)

2019-11-15 07:37 UTC, levy9527 requested changes

2019-11-15 07:37 UTC, levy9527 commented on package.json
> +    "husky": "^3.0.9",
组件的 husky 是 1.x ，跟组件保持一致

2019-11-18 02:20 UTC, levy9527 requested changes

2019-11-18 02:20 UTC, levy9527 commented on package.json
> +    "husky": "^3.0.9",
https://github.com/typicode/husky/releases/tag/v3.0.0

2019-11-21 07:32 UTC, xrr2016 approved these changes

2019-11-21 15:13 UTC, snowlocked approved these changes

2019-11-21 15:14 UTC, snowlocked approved these changes

2019-11-22 02:10 UTC, levy9527 approved these changes

2019-11-22 02:11 UTC, merged