docs: 增加主题维护规范
FEMessage/element pull request #16
Opened 2019-11-25 08:43 UTC by lianghx-319

## Docs

为了适应项目组的需求，需要更新主题的维护方式。方便项目组更新主题组件

2019-11-25 13:00 UTC, donaldshen commented on README.md
> +git checkout -b only-component new-theme
生成 theme 是从 dev 切分支吧？

2019-11-25 13:07 UTC, donaldshen commented on README.md
> +Why checkout from branch `only-component`, see [Contributing Guide](https://github.com/femessage/element/blob/master/.github/CONTRIBUTING.zh-CN.md)
The reason to checkout ...

2019-11-25 13:09 UTC, donaldshen approved these changes

2019-11-27 02:42 UTC, levy9527 requested changes

2019-11-27 02:42 UTC, levy9527 commented on .github/CONTRIBUTING.zh-CN.md
> +- 由于本仓库的主题会随着业务不断更新，为了防止不必要的主题样式污染。自定义主题需要根据 `only-component` 分支生成主题
补充语雀链接

2019-11-27 11:30 UTC, merged