feat: 增强 avatar
FEMessage/element pull request #76
Opened 2020-09-16 08:47 UTC by gd4Ark

## Why
1. 图片无法加载或 src 为空时，可以把姓名缩写作为占位符
2. hover 时可以显示姓名

![image](https://user-images.githubusercontent.com/27952659/93313983-c3cd6c00-f83b-11ea-9d96-87baf88e09cd.png)

## How
![image](https://user-images.githubusercontent.com/27952659/93314070-e2cbfe00-f83b-11ea-8ca8-03ec2c9c97cf.png)

附上设计文档：[链接](https://deepexi.yuque.com/docs/share/65ea6730-cc40-42ea-a7e7-57dc6f590d73)

## Preview
![2020-09-16 16 46 13](https://user-images.githubusercontent.com/27952659/93314353-39393c80-f83c-11ea-892f-b68aa9df12b0.gif)

## Docs
- [x] 中文文档
- [x] 英文文档

2020-09-17 11:10 UTC, snowlocked commented on packages/avatar/src/main.vue
> +      if (name || tooltip) {
用不上的class属性先去掉

2020-09-18 08:40 UTC, levy9527 requested changes
api命名改下：
1. name => text
2. initialFormatter => text-formatter

2020-09-18 08:42 UTC, snowlocked approved these changes

2020-09-23 02:43 UTC, levy9527 commented on examples/docs/en-US/avatar.md
> +When there is an incoming text or tooltip support hover display, you can also customize tooltip content by tooltip.
英文不顺畅

2020-09-23 04:26 UTC, colmugx commented on packages/avatar/src/main.vue
> +</script>
补一个结束空行

2020-09-23 04:27 UTC, colmugx commented on packages/theme-chalk/src/avatar.scss
> +    position: relative;
缩进

2020-09-23 04:27 UTC, colmugx commented on test/unit/index.js
> +const testsContext = require.context('./specs', true, /\avatar.spec$/);
恢复测试

2020-09-23 06:28 UTC, colmugx approved these changes

2020-09-24 09:03 UTC, levy9527 approved these changes

2020-09-24 09:05 UTC, merged